databaseChangeLog:
  - changeSet:
      id: 004-revert-ticket-date
      author: gwuy
      changes:

        - sql:
            sql: |
              ALTER TABLE tickets
              ALTER COLUMN start_at TYPE DATE
              USING to_timestamp(start_at / 1000)::date;

        - sql:
            sql: |
              ALTER TABLE tickets
              ALTER COLUMN end_at TYPE DATE
              USING to_timestamp(end_at / 1000)::date;