databaseChangeLog:
  - changeSet:
      id: 005-create-ticket-types-table
      author: hrm-service
      changes:
        - createTable:
            tableName: ticket_types
            columns:
              - column:
                  name: ticket_type_id
                  type: bigint
                  constraints:
                    nullable: false
                    primaryKey: true
              - column:
                  name: type_name
                  type: varchar(255)
              - column:
                  name: description
                  type: text
              - column:
                  name: created_at
                  type: bigint
              - column:
                  name: updated_at
                  type: bigint
              - column:
                  name: updated_by
                  type: bigint
              - column:
                  name: created_by
                  type: bigint