databaseChangeLog:
  - include:
      file: db/changelog/tables/001-positions.yaml
  - include:
      file: db/changelog/tables/002-work_locations.yaml
  - include:
      file: db/changelog/tables/003-users.yaml
  - include:
      file: db/changelog/tables/004-ticket_types.yaml
  - include:
      file: db/changelog/tables/005-tickets.yaml
  - include:
      file: db/changelog/tables/006-leave_types.yaml
  - include:
      file: db/changelog/tables/007-leave_requests.yaml
  - include:
      file: db/changelog/tables/008-remote_requests.yaml
  - include:
      file: db/changelog/tables/009-ticket_approvals.yaml
  - include:
      file: db/changelog/tables/010-attendance_logs.yaml
  - include:
      file: db/changelog/tables/011-feedback_types.yaml
  - include:
      file: db/changelog/tables/012-anonymous_feedbacks.yaml
  - include:
      file: db/changelog/tables/013-feedback_messages.yaml
  - include:
      file: db/changelog/tables/014-feedback_attachments.yaml
  - include:
      file: db/changelog/tables/015-avatars.yaml
  - include:
      file: db/changelog/tables/016-cv.yaml
  - include:
      file: db/changelog/tables/017-quick_notes.yaml
  - include:
      file: db/changelog/tables/018-org_chart_nodes.yaml
  - include:
      file: db/changelog/tables/019-indexes.yaml